ALTER TYPE "CandidateStatus" RENAME TO "CandidateStatus_old";

CREATE TYPE "CandidateStatus" AS ENUM (
  'RECOMMENDED',
  'INVITED',
  'FIRST_INTERVIEW',
  'SECOND_INTERVIEW',
  'CROSS_INTERVIEW',
  'FINAL_INTERVIEW',
  'PASSED',
  'OFFER',
  'ONBOARD'
);

ALTER TABLE "Candidate"
  ALTER COLUMN "status" DROP DEFAULT,
  ALTER COLUMN "status" TYPE "CandidateStatus"
  USING (
    CASE "status"::text
      WHEN 'NEW' THEN 'RECOMMENDED'
      WHEN 'SCREENING' THEN 'INVITED'
      WHEN 'WRITTEN_TEST' THEN 'INVITED'
      WHEN 'FIRST_INTERVIEW' THEN 'FIRST_INTERVIEW'
      WHEN 'SECOND_INTERVIEW' THEN 'SECOND_INTERVIEW'
      WHEN 'FINAL_INTERVIEW' THEN 'FINAL_INTERVIEW'
      WHEN 'OFFER' THEN 'OFFER'
      WHEN 'ONBOARD' THEN 'ONBOARD'
      ELSE 'RECOMMENDED'
    END
  )::"CandidateStatus",
  ALTER COLUMN "status" SET DEFAULT 'RECOMMENDED';

ALTER TABLE "RecruitmentLog"
  ALTER COLUMN "fromStatus" TYPE "CandidateStatus"
  USING (
    CASE
      WHEN "fromStatus" IS NULL THEN NULL
      WHEN "fromStatus"::text = 'NEW' THEN 'RECOMMENDED'
      WHEN "fromStatus"::text = 'SCREENING' THEN 'INVITED'
      WHEN "fromStatus"::text = 'WRITTEN_TEST' THEN 'INVITED'
      WHEN "fromStatus"::text = 'FIRST_INTERVIEW' THEN 'FIRST_INTERVIEW'
      WHEN "fromStatus"::text = 'SECOND_INTERVIEW' THEN 'SECOND_INTERVIEW'
      WHEN "fromStatus"::text = 'FINAL_INTERVIEW' THEN 'FINAL_INTERVIEW'
      WHEN "fromStatus"::text = 'OFFER' THEN 'OFFER'
      WHEN "fromStatus"::text = 'ONBOARD' THEN 'ONBOARD'
      ELSE 'RECOMMENDED'
    END
  )::"CandidateStatus",
  ALTER COLUMN "toStatus" TYPE "CandidateStatus"
  USING (
    CASE "toStatus"::text
      WHEN 'NEW' THEN 'RECOMMENDED'
      WHEN 'SCREENING' THEN 'INVITED'
      WHEN 'WRITTEN_TEST' THEN 'INVITED'
      WHEN 'FIRST_INTERVIEW' THEN 'FIRST_INTERVIEW'
      WHEN 'SECOND_INTERVIEW' THEN 'SECOND_INTERVIEW'
      WHEN 'FINAL_INTERVIEW' THEN 'FINAL_INTERVIEW'
      WHEN 'OFFER' THEN 'OFFER'
      WHEN 'ONBOARD' THEN 'ONBOARD'
      ELSE 'RECOMMENDED'
    END
  )::"CandidateStatus";

ALTER TABLE "RecruitmentApplication"
  ALTER COLUMN "status" DROP DEFAULT,
  ALTER COLUMN "status" TYPE "CandidateStatus"
  USING (
    CASE "status"::text
      WHEN 'NEW' THEN 'RECOMMENDED'
      WHEN 'SCREENING' THEN 'INVITED'
      WHEN 'WRITTEN_TEST' THEN 'INVITED'
      WHEN 'FIRST_INTERVIEW' THEN 'FIRST_INTERVIEW'
      WHEN 'SECOND_INTERVIEW' THEN 'SECOND_INTERVIEW'
      WHEN 'FINAL_INTERVIEW' THEN 'FINAL_INTERVIEW'
      WHEN 'OFFER' THEN 'OFFER'
      WHEN 'ONBOARD' THEN 'ONBOARD'
      ELSE 'RECOMMENDED'
    END
  )::"CandidateStatus",
  ALTER COLUMN "status" SET DEFAULT 'RECOMMENDED';

DROP TYPE "CandidateStatus_old";
